# .github/workflows/publish.yml

name: Publish to npm

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a Node.js version compatible with your project
          registry-url: "https://registry.npmjs.org" # Important for npm authentication

      - name: Install dependencies
        run: npm install

      - name: Build package
        # Crucial: The package must be built BEFORE publishing.
        # This runs the 'build' script defined in your package.json.
        run: npm run build

      - name: Publish to npm
        env:
          # Use a GitHub Secret for your npm token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing contents of dist/:"
          ls -la dist/

          # Check if the package version exists on npm to avoid re-publishing identical versions
          # This is a safety check; ideally, you should bump version manually before merge
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")

          NPM_REGISTRY_URL="https://registry.npmjs.org"

          # Check if version already exists
          npm view "$PACKAGE_NAME@$PACKAGE_VERSION" > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "Package version $PACKAGE_VERSION already exists on npm. Skipping publish."
            exit 0
          else
            echo "Package version $PACKAGE_VERSION is new. Attempting to publish."
            # Publish the package.
            # Use --access public for unscoped public packages or scoped public packages.
            # Omit --access public if your scoped package is intended to be private.
            npm publish --access public --verbose
          fi
